version: '3'
services:
  mysqlos:
    image: mysql:5.7
    volumes:
      - mysql_storage_new:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: sql_password
      MYSQL_USER: sqlname
      MYSQL_PASSWORD: sqlpassword
      MYSQL_DATABASE: mydb


  joomlaos:
    image:  joomla:3.9-php7.3-apache
    restart: always
    depends_on:
      - mysqlos
    ports:
      - 8080:80
    environment:
      JOOMLA_DB_HOST: mysql:3306
      JOOMLA_DB_USER: zoomlauser
      JOOMLA_DB_PASSWORD: password
      JOOMLA_DB_NAME: mydb
    volumes:
      - jm_storage_new:/var/www/html
volumes:
  jm_storage_new:
  mysql_storage_new:
